apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: polar
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: config-serivce
          image: config-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          resources:
            limits:
              cpu: "500m"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
