apiVersion: v1
kind: Service
metadata:
  name:  config-service
  namespace:  polar
spec:
  selector:
    app:  Selector Label
  type:  ClusterIP
  ports:
  - protocol: TCP
    port:  80
    targetPort:  8888